# Generated by Django 5.2.9 on 2025-12-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('subject', models.CharField(choices=[('math', 'الرياضيات'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('english', 'اللغة الانجليزية'), ('nature', 'علوم الطبيعة والحياة'), ('physics', 'الفيزياء'), ('social', 'الإجتماعيات')], max_length=20, verbose_name='المادة')),
                ('exam_type', models.CharField(choices=[('exam', 'اختبار'), ('test', 'فرض')], max_length=10, verbose_name='النوع')),
                ('academic_year', models.CharField(choices=[('year1', 'السنة الأولى'), ('year2', 'السنة الثانية'), ('year3', 'السنة الثالثة'), ('year4', 'السنة الرابعة')], max_length=10, verbose_name='السنة الدراسية')),
                ('correction_status', models.CharField(choices=[('available', 'متوفر التصحيح'), ('not_available', 'غير متوفر التصحيح')], max_length=20, verbose_name='حالة التصحيح')),
                ('exam_file', models.FileField(upload_to='exams/%Y/%m/', verbose_name='ملف الاختبار')),
                ('correction_file', models.FileField(blank=True, null=True, upload_to='corrections/%Y/%m/', verbose_name='ملف التصحيح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'اختبارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'academic_year', 'exam_type'], name='lessons_exa_subject_2e9cda_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('subject', models.CharField(choices=[('math', 'الرياضيات'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('english', 'اللغة الانجليزية'), ('nature', 'علوم الطبيعة والحياة'), ('physics', 'الفيزياء'), ('social', 'الإجتماعيات')], max_length=20, verbose_name='المادة')),
                ('academic_year', models.CharField(choices=[('year1', 'السنة الأولى'), ('year2', 'السنة الثانية'), ('year3', 'السنة الثالثة'), ('year4', 'السنة الرابعة')], max_length=10, verbose_name='السنة الدراسية')),
                ('pdf_file', models.FileField(upload_to='lessons/%Y/%m/', verbose_name='ملف الدرس PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'academic_year'], name='lessons_les_subject_eddd11_idx')],
            },
        ),
    ]
