# Generated by Django 5.2.9 on 2025-12-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان النصيحة')),
                ('subject', models.CharField(choices=[('math', 'الرياضيات'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('english', 'اللغة الانجليزية'), ('nature', 'علوم الطبيعة والحياة'), ('physics', 'الفيزياء'), ('social', 'الإجتماعيات')], max_length=20, verbose_name='الموضوع')),
                ('academic_year', models.CharField(choices=[('year1', 'السنة الأولى'), ('year2', 'السنة الثانية'), ('year3', 'السنة الثالثة'), ('year4', 'السنة الرابعة')], max_length=10, verbose_name='السنة الدراسية')),
                ('content', models.TextField(verbose_name='محتوى النصيحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نصيحة',
                'verbose_name_plural': 'نصائح',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'academic_year'], name='lessons_tip_subject_a2da8a_idx')],
            },
        ),
    ]
