# Generated by Django 5.2.9 on 2025-12-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, unique=True, verbose_name='كلمة السر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'كلمة السر',
                'verbose_name_plural': 'كلمات السر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('math', 'الرياضيات'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('english', 'اللغة الانجليزية'), ('nature', 'علوم الطبيعة والحياة'), ('physics', 'الفيزياء'), ('social', 'الإجتماعيات'), ('islamic', 'التربية الإسلامية')], max_length=20, verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('math', 'الرياضيات'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('english', 'اللغة الانجليزية'), ('nature', 'علوم الطبيعة والحياة'), ('physics', 'الفيزياء'), ('social', 'الإجتماعيات'), ('islamic', 'التربية الإسلامية')], max_length=20, verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='subject',
            field=models.CharField(choices=[('math', 'الرياضيات'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('english', 'اللغة الانجليزية'), ('nature', 'علوم الطبيعة والحياة'), ('physics', 'الفيزياء'), ('social', 'الإجتماعيات'), ('islamic', 'التربية الإسلامية')], max_length=20, verbose_name='الموضوع'),
        ),
    ]
